//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcTM.WebAPI.DataLayer.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jctmEntities : DbContext
    {
        public jctmEntities()
            : base("name=jctmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Temperature> Temperatures { get; set; }
    
        public virtual ObjectResult<WEBAPI_getLatestTemperatureSP_Result> WEBAPI_getLatestTemperatureSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEBAPI_getLatestTemperatureSP_Result>("WEBAPI_getLatestTemperatureSP");
        }
    }
}
